### ISSUE TITLE
activate error

### ISSUE THREAD

**Issue by Sizoberz** [ctsmedia/contao-phpbb-bridge-bundle#41]
Installation work fine until point 6. I want to activate the contao extention ist give a green success but then I can´t access any page on front- or backend getting this error
`[phpBB Debug] PHP Warning: in file /XXX/vendor/ctsmedia/contao-phpbb-bridge-bundle/src/Resources/phpBB/ctsmedia/contaophpbbbridge/contao/Connector.php on line 32: require_once(/XXX/vendor/ctsmedia/contao-phpbb-bridge-bundle/src/Resources/phpBB/ctsmedia/contaophpbbbridge/contao/../vendor/autoload.php): failed to open stream: No such file or directory

Fatal error: require_once(): Failed opening required '/XXX/vendor/ctsmedia/contao-phpbb-bridge-bundle/src/Resources/phpBB/ctsmedia/contaophpbbbridge/contao/../vendor/autoload.php' (include_path='.:/usr/lib/php7.2') in /XXX/vendor/ctsmedia/contao-phpbb-bridge-bundle/src/Resources/phpBB/ctsmedia/contaophpbbbridge/contao/Connector.php on line 32
`
Can anybody help me fix that?

**Comment by DanielSchwiperich** [comment]
Hi @Sizoberz, 

which contao version are you using?
Where did you put the forum path wise and what did you put in the form for the the forum path?

**Comment by Sizoberz** [comment]
Hi @DanielSchwiperich,

I use Contao version 4.5.10.
phpBB 3.2.2 is installed inf folder web/phpBB3
In Contao for the PhpBB Forum Site I put "phpBB3" as Forum Url Alias and phpBB Install path

**Comment by DanielSchwiperich** [comment]
I think I missed to add the the vendor stuff in last package for phpbb. Could you pls do step 3 from the install docs  => Go to  `/XXX/vendor/ctsmedia/contao-phpbb-bridge-bundle/src/Resources/phpBB/ctsmedia/contaophpbbbridge` and run `composer install`

**Comment by Sizoberz** [comment]
Thank you @DanielSchwiperich,
but I don´t know what exactly to do. I guess you mean run the composer per ssh.
I use putty, go to the mentioned folder and enter "composer install", but get error:
`-bash: composer: command not found`
I´m no developer, just like to create website with contao and so I´m not very used to work with console :-(
Can you please give me some more exact instuction how to install the needed http library?
BTW can we chat in german, think it would be easier, or do you think it should be interesting for international users ?

**Comment by DanielSchwiperich** [comment]
Ja können wir auch in Deutsch fortführen 😄 

Ich versuche im Laufe der Woche ein kleines Update zu machen, was die benötigten Dateien direkt wieder enthält, so dass du ohne composer auskommst.

**Comment by Sizoberz** [comment]
Super, Danke Dir @DanielSchwiperich!

**Comment by Sizoberz** [comment]
Hallo @DanielSchwiperich,
bis wann meinst das Update zur Verfügung stellen zu können?

**Comment by DanielSchwiperich** [comment]
Hi @Sizoberz,
am We oder Anfang der kommenden Woche. 
Sorry war zu stressig die letzten Tage

**Comment by DanielSchwiperich** [comment]
Hi @Sizoberz, 
ich habe gerade 1.2.0 mit den fehlen Sorucen released. Bitte versuche es nochmal (du musst glaube ich contao manager das package abwählen so dass es deinstalliert wird und dann nochmal installieren).

Gib dann Bescheid ob es geklappt hat.

**Comment by DanielSchwiperich** [comment]
Dein 2. Problem aus #42  werde ich in 1.2.1 beheben.
Siehe #43

**Comment by Sizoberz** [comment]
Danke @DanielSchwiperich, die installation ist jetzt durchgelaufen. Allerdings werde ich nicht bei phpBB angemeldet. Bei bereits bestehenden usern kommt "Konnte nicht bei Contao einloggen. Bitte erneut versuchen oder Support kontaktieren." Bei usern die ich nach der Installation anlege kommt "Du hast ein falsches Passwort angegeben. Bitte prüfe dein Passwort und versuche es erneut. Wenn du weiterhin auf Probleme stößt, wende dich bitte an die Board-Administration." obwohl das Passwort definitiv passt.
Das wirklich schlechte ist das ich mich auch mit meinem Admin account nicht mehr bei phpBB anmelden kann.

**Comment by Sizoberz** [comment]
und der Logout im Contao Frontend funktioniert auch nicht mehr

**Comment by Sizoberz** [comment]
Habe nochmal alle Abhängigkeiten installiert und da ging einiges + eine DB-Tabelle wurde nochmal hinzugefügt. Verhalten ist aber immernoch gleich. Habe phpBB und das Modul nochmal neu installiert und die Authentifizierung im phpBB nicht aktiviert, dass ich mich dort noch anmelden kann.

**Comment by Sizoberz** [comment]
Diese Meldung kommt im Contao Manager

Package heimrichhannot/contao-ajax is abandoned, you should avoid using it. Use heimrichhannot/contao-ajax-bundle instead.
Package heimrichhannot/contao-be_explanation is abandoned, you should avoid using it. Use heimrichhannot/contao-be_explanation-bundle instead.
Package heimrichhannot/contao-fieldpalette is abandoned, you should avoid using it. Use heimrichhannot/contao-fieldpalette-bundle instead.
Package heimrichhannot/contao-multifileupload is abandoned, you should avoid using it. Use heimrichhannot/contao-multifileupload-bundle instead.
Package heimrichhannot/contao-request is abandoned, you should avoid using it. Use heimrichhannot/contao-request-bundle instead.
Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.

**Comment by Sizoberz** [comment]
Das Nachinstallieren der Module hat nichts gebracht es kommt immernoch die gleiche Meldung

**Comment by DanielSchwiperich** [comment]
Diese Abhängigkeiten haben nichts mit dem Modul zu tun. 

Hast du alles aus https://github.com/ctsmedia/contao-phpbb-bridge-bundle/blob/master/doc/faq-troubleshooting.md 
geprüft?

Bitte schau auch mal in den Contao Log und in den Log auf phpbb seite für das Modul: 
`phpbbforumdir/ext/ctsmedia/contaophpbbbridge/`

**Comment by DanielSchwiperich** [comment]
Ich habe gerade auch ein Update released was den Bug z.b. mit cache leeren behebt
https://github.com/ctsmedia/contao-phpbb-bridge-bundle/releases/tag/1.2.1

ggf. behebt das auch deine Probleme gleich mit. @Sizoberz

**Comment by Sizoberz** [comment]
Hallo @DanielSchwiperich,
nach dem Update auf 1.2.1 funktioniert phpBB gar nicht mehr:
Fatal error: Uncaught Twig_Error_Loader: Unable to find template "@ctsmedia_contaophpbbbridge/event/overall_header_stylesheets_after.html" (looked into: /XXX/vendor/ctsmedia/contao-phpbb-bridge-bundle/src/Resources/phpBB/ctsmedia/contaophpbbbridge/styles/all/template, /XXX/vendor/ctsmedia/contao-phpbb-bridge-bundle/src/Resources/phpBB/ctsmedia/contaophpbbbridge/styles/all/template) in "overall_header.html" at line 72. in /XXX/web/phpBB3/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:232 Stack trace: #0 /XXX/web/phpBB3/phpbb/template/twig/loader.php(135): Twig_Loader_Filesystem->findTemplate('@ctsmedia_conta...') #1 /XXX/web/phpBB3/vendor/twig/twig/lib/Twig/Loader/Filesystem.php(150): phpbb\template\twig\loader->findTemplate('@ctsmedia_conta...') #2 /XXX/web/phpBB3/vendor/twig/twig/lib/Twig/Environment.php(330): Twig_Loader_Fil in /homepages/27/d225070431/XXX/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 232

soll ich es komplett neu installieren?

**Comment by Sizoberz** [comment]
Hab es neu installiert mit Version 1.2.1. Die Fehlermeldung von oben kommt nicht mehr und die Installation lief durch. Logout funktioniert jetzt wieder im Contao.
Login von Benutzern in phpBB verhält sich aber immer noch gleich.
Benutzer aus Contao können sich nicht in phpBB anmelden, auch Benutzer, die nach der Installation angelgt werden sind nicht in phpBB verfügbar.

**Comment by Sizoberz** [comment]
Das Forum cache leeren geht auch noch nicht
Operation timed out after 5001 milliseconds with 0 bytes received

**Comment by DanielSchwiperich** [comment]
Schau mal bitte in den Contao Log und in den Log auf phpbb seite für das Modul:
phpbbforumdir/ext/ctsmedia/contaophpbbbridge/

Da sollten vermutlich Fehlermeldungen stehen. Dann können wir dem auf dem Grund gehen

**Comment by Sizoberz** [comment]
Hier die bridge_error.log

[2018-07-26 21:57:50] bridge_connector.ERROR: __LAYOUT__--------------------------- [] []
[2018-07-26 21:57:50] bridge_connector.ERROR: Json Response expected. Got:  {"status":302} []
[2018-07-26 21:57:50] bridge_connector.ERROR: Set-Cookies:  ["PHPSESSID=74e6fadc815532b2acf37ba4df85f48b; path=/; httponly\r\ncsrf_https-contao_csrf_token=pKaIromai47mgooosk5cuSgEuDUk7xHmHGpqunmbyfk; expires=Fri, 27-Jul-2018 19:57:50 GMT; Max-Age=86400; path=/; secure; httponly; samesite=lax"] []
[2018-07-26 21:57:50] bridge_connector.ERROR: REQ--------------------------- [] []
[2018-07-26 21:57:50] bridge_connector.ERROR: Inc ath ["/phpBB3/index.php"] []
[2018-07-26 21:57:50] bridge_connector.ERROR: Path ["/phpbb_bridge/layout"] []
[2018-07-26 21:57:50] bridge_connector.ERROR: Cookies ["csrf_https-contao_csrf_token=pKaIromai47mgooosk5cuSgEuDUk7xHmHGpqunmbyfk; csrf_https-contao_csrf_token=pKaIromai47mgooosk5cuSgEuDUk7xHmHGpqunmbyfk; phpbb3_azqrr_u=1; phpbb3_azqrr_k=; phpbb3_azqrr_sid=1d8174a72ad21e83dab04b8259c038f8"] []
[2018-07-26 21:57:50] bridge_connector.ERROR: Append [""] []
[2018-07-26 21:58:07] bridge_connector.ERROR: __LAYOUT__--------------------------- [] []
[2018-07-26 21:58:07] bridge_connector.ERROR: Json Response expected. Got:  {"status":403} []
[2018-07-26 21:58:07] bridge_connector.ERROR: Set-Cookies:  ["PHPSESSID=2a0aeb649b7f316718ecca8f07f38b74; path=/; httponly\r\ncsrf_https-contao_csrf_token=pKaIromai47mgooosk5cuSgEuDUk7xHmHGpqunmbyfk; expires=Fri, 27-Jul-2018 19:58:07 GMT; Max-Age=86400; path=/; secure; httponly; samesite=lax"] []
[2018-07-26 21:58:07] bridge_connector.ERROR: REQ--------------------------- [] []
[2018-07-26 21:58:07] bridge_connector.ERROR: Inc ath ["/phpBB3/index.php"] []
[2018-07-26 21:58:07] bridge_connector.ERROR: Path ["/phpbb_bridge/layout"] []
[2018-07-26 21:58:07] bridge_connector.ERROR: Cookies ["csrf_https-contao_csrf_token=pKaIromai47mgooosk5cuSgEuDUk7xHmHGpqunmbyfk; csrf_https-contao_csrf_token=pKaIromai47mgooosk5cuSgEuDUk7xHmHGpqunmbyfk; phpbb3_azqrr_u=1; phpbb3_azqrr_k=; phpbb3_azqrr_sid=a6c7d97c5800147510eb7a2131843f07; PHPSESSID=2a0aeb649b7f316718ecca8f07f38b74"] []
[2018-07-26 21:58:07] bridge_connector.ERROR: Append [""] []

**Comment by Sizoberz** [comment]
Verwende das RockSolid OpenSouce Theme - hängt es damit zusammen?

**Comment by DanielSchwiperich** [comment]
@Sizoberz was ich gerade sehe, du verwendest 4.5. In 4.5 haben die Jungs das komplette Login System geändert. Sehr wahrscheinlich gibts da eine Inkompatibilität. 
https://github.com/contao/core-bundle/blob/4.5/CHANGELOG.md#450-rc1-2017-12-12

Ich habe das damit noch nicht getestet. Wir haben gerade intern selber ein Projekt wo wir die Bridge einsetzen und noch prüfen auf 4.5 zu wechseln anstatt die 4.4 zu nutzen. 
Ich kann aber noch nicht genau sagen wann ich dazu komme die Bridge und 4.5 kompatibel zu machen

**Comment by Sizoberz** [comment]
Ja ein anderes Modul hat auch schon Probleme gemacht. Zurück auf 4.4.12 könnte ich auch nicht mehr.

**Comment by Sizoberz** [comment]
Konnte jetzt doch zurück auf 4.4.12 - Login geht aber immer noch nicht - oder phpBB und Bridge noch neu installieren?
